### ISSUE TITLE
Pause routine is dubious

### ISSUE THREAD

**Issue by claesbert** [claesbert/PlexampStatusPage#3]
pause routine is dubious and not really working

**Comment by protobear** [comment]
Unclear what this means, please elaborate. 
What is the problematic behavior?

**Comment by claesbert** [comment]
It has to be evaluated once the progress bar is fixed. When pauzing before,
the time ran for 5 seconds went back five seconds and repeated this;)

Op zo 29 sep. 2024 16:42 schreef Marnick ***@***.***>:
